[package]
name = "swc_ecma_visit_macros"
version = "0.1.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
swc_macros_common = { version = "0.3", path ="../../../macros/common" }
proc-macro2 = "1"
pmutil = "0.5.1"
quote = "1"
syn = { version = "1", features = ["parsing", "full"] }
Inflector = "0.11.4"